name: Push to Prod
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push to prod
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: prod
        message: Release to prod
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
